# Generated by Django 5.0.2 on 2024-02-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('age', models.IntegerField()),
                ('id_no', models.IntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='age',
        ),
        migrations.RemoveField(
            model_name='students',
            name='date_of_birth',
        ),
    ]
