# Generated by Django 5.0.2 on 2024-02-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelapp', '0002_docters_parents_remove_students_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=25)),
                ('Time', models.DateTimeField(max_length=15)),
            ],
        ),
    ]
